baseURL = "https://blog.pjmcode.top/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

# 网站标题
title = "江明说|Jimmy Talk"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true

defaultContentLanguage = "zh-cn"

# 默认每页列表显示的文章数目
paginate = 12
# 谷歌分析代号 [UA-XXXXXXXX-X]
# googleAnalytics = ""
# 版权描述，仅仅用于 SEO
copyright = ""

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# 作者配置
[author]
email = "panjm2001@126.com"
link = "https://github.com/pjimming/"
name = "潘江明"

# 菜单配置
[menu]
[[menu.main]]
identifier = "posts"
weight = 1
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='fa-solid fa-box-archive'></i>"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
name = "所有文章"
post = ""
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
[[menu.main]]
identifier = "tags"
name = "标签"
post = ""
pre = "<i class='fa-solid fa-tag'></i>"
title = ""
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "categories"
name = "分类"
post = ""
pre = "<i class='fa-solid fa-table-list'></i>"
title = ""
url = "/categories/"
weight = 3
[[menu.main]]
identifier = "friend"
name = "友链"
post = ""
pre = "<i class='fa-solid fa-user-group'></i>"
title = ""
url = "/friend/"
weight = 5
[[menu.main]]
identifier = "book-list"
name = "书单"
post = ""
pre = "<i class='fa-solid fa-book'></i>"
title = ""
url = "/book-list/"
weight = 6
[[menu.main]]
identifier = "about"
name = "关于"
post = ""
pre = "<i class='fa-regular fa-address-card'></i>"
title = ""
url = "/about/"
weight = 10

[params]
# 网站默认主题样式 ["auto", "light", "dark"]
defaultTheme = "auto"
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = "https://github.com/pjimming/blog"
#  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
#  日期格式
dateFormat = "2006-01-02"
# 网站标题, 用于 Open Graph 和 Twitter Cards
title = "江明说|Jimmy Talk"
# 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
description = "江明说"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/logo.png"]

# 页面头部导航栏配置
[params.header]
# 桌面端导航栏模式 ["fixed", "normal", "auto"]
desktopMode = "fixed"
# 移动端导航栏模式 ["fixed", "normal", "auto"]
mobileMode = "auto"
#  页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = "/images/favicon.ico"
# 标题名称
name = "Jimmy Talk"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ''
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ''
#  是否为标题显示打字机动画
typeit = false

# 页面底部信息配置
[params.footer]
enable = true
#  自定义内容 (支持 HTML 格式)
custom = ''
#  是否显示 Hugo 和主题信息
hugo = true
#  是否显示版权信息
copyright = true
#  是否显示作者
author = true
# 网站创立年份
since = 2024
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = '<a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=备案编号" target="_blank">浙ICP备2024074882号</a>'
# 许可协议信息 (支持 HTML 格式)
license = ''

#  Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

#  List (目录或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

#  应用图标配置
[params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
title = "江明说"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = "/images/favicon.ico"
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10磁贴颜色
tileColor = "#da532c"

#  搜索配置
[params.search]
enable = true
# 搜索引擎的类型 ["lunr", "algolia"]
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
#  最大结果数目
maxResultLength = 10
#  结果内容片段长度
snippetLength = 50
#  搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#  是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[params.search.algolia]
appID = ""
index = ""
searchKey = ""

# 主页配置
[params.home]
#  RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
avatarURL = "/images/avatar.jpeg"
#  主页显示的网站标题 (支持 HTML 格式)
title = "江明说"
# 主页显示的网站副标题 (允许 HTML 格式)
subtitle = "不积跬步，无以至千里。不积小流，无以成江海。"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
#  免责声明 (支持 HTML 格式)
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 6
#  被 params.page 中的 hiddenFromHomePage 替代
# 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
defaultHiddenFromHomePage = false

# Display a message at the beginning of an article to warn the readers that it's content may be outdated.
# 在文章末尾显示提示信息，提醒读者文章内容可能过时。
[params.outdatedInfoWarning]
after = "，请鉴别其时效性，以免造成不必要的麻烦。" 
before = "这篇文章最后修改于" 
enable = true 
hint = 90 # Display hint if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示提醒
warn = 180 # Display warning if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示警告

# 作者的社交信息设置
[params.social]
Angellist = "" 
Bandcamp = "" 
Behance = "" 
Bilibili = "" 
Bitbucket = "" 
Codepen = "" 
Deviantart = "" 
Devto = "" 
Discord = "" 
DiscordInvite = "" 
Douban = "" 
Dribbble = "" 
Email = "panjm2001@126.com" 
Facebook = "" 
Fivehundredpx = "" 
Flickr = "" 
Foursquare = "" 
FreeCodeCamp = "" 
GitHub = "pjimming" 
Gitea = "" 
Gitlab = "" 
Goodreads = "" 
Googlescholar = "" 
HackTheBox = "" 
Hackernews = "" 
Instagram = "" 
Jsfiddle = "" 
Kaggle = "" 
Keybase = "" 
Kickstarter = "" 
Lastfm = "" 
Lichess = "" 
Linkedin = "" 
Mastodon = "" 
Matrix = "" 
MediaWiki = "" 
Medium = "" 
Mix = "" 
ORCID = "" 
Odnoklassniki = "" 
Patreon = "" 
Paypal = "" 
Phone = "" 
Pinterest = "" 
Pleroma = "" 
Plume = "" 
Quora = "" 
RSS = true # 
Reddit = "" 
Researchgate = "" 
RootMe = "" 
Skype = "" 
Slidershare = "" 
Snapchat = "" 
Soundcloud = "" 
Spotify = "" 
Stackoverflow = "" 
Steam = "" 
Strava = "" 
Telegram = "" 
Thingiverse = "" 
Tumblr = "" 
Twitch = "" 
Twitter = "" 
VK = "" 
Vine = "" 
Weibo = "" 
Whatsapp = "" 
Wordpress = "" 
XMPP = "" 
Xing = "" 
Youtubechannel = "" 
Youtubecustom = "" 
Youtubelegacy = "" 
Zhihu = "" 

#  文章页面全局配置
[params.page]
#  是否在主页隐藏一篇文章
hiddenFromHomePage = false
#  是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
#  是否使用 twemoji
twemoji = false
# 是否使用 lightgallery
lightgallery = true
#  是否使用 ruby 扩展语法
ruby = true
#  是否使用 fraction 扩展语法
fraction = true
#  是否使用 fontawesome 扩展语法
fontawesome = true
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
#  是否在 RSS 中显示全文内容
rssFullText = false
#  目录配置
[params.page.toc]
# 是否使用目录
enable = true
#  是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = true
#  代码配置
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
# 默认展开显示的代码行数
maxShownLines = 50
#  KaTeX 数学公式
[params.page.math]
enable = true
#  默认行内定界符是 $ ... $ 和 \( ... \)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
#  默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
blockLeftDelimiter = ""
blockRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true
#  Mapbox GL JS 配置
[params.page.mapbox]
# Mapbox GL JS 的 access token
accessToken = "pk.eyJ1Ijoic2NvdGhpcyIsImEiOiJjaWp1Y2ltYmUwMDBicmJrdDQ4ZDBkaGN4In0.sbihZCZJ56-fsFNKHXF8YQ"
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true
#  文章页面的分享信息设置
[params.page.share]
Baidu = false
Blogger = false
Buffer = false
Evernote = false
Facebook = true
Flipboard = false
HackerNews = true
Instapaper = false
Line = true
Linkedin = false
Mix = false
Odnoklassniki = false
Pinterest = false
Pocket = false
Reddit = false
Skype = false
Trello = false
Tumblr = false
Twitter = true
VK = false
Weibo = true
Whatsapp = false
Xing = false
enable = true
#  评论系统设置
[params.page.comment]
enable = true
# Disqus 评论系统设置
[params.page.comment.disqus]
# 
enable = false
# Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
shortname = ""
# Gitalk 评论系统设置
[params.page.comment.gitalk]
# 
clientId = ""
clientSecret = ""
enable = false
owner = ""
repo = ""
# Valine 评论系统设置
[params.page.comment.valine]
appId = ""
appKey = ""
avatar = "mp"
enable = false
meta = ""
pageSize = 10
placeholder = ""
# 为空时自动适配当前主题 i18n 配置
enableQQ = false
highlight = true
lang = ""
recordIP = true
serverURLs = ""
visitor = true
#  emoji 数据文件名称, 默认是 "google.yml"
# ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
# 位于 "themes/LoveIt/assets/lib/valine/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/lib/valine/emoji/"
emoji = ""
# Facebook 评论系统设置
[params.page.comment.facebook]
appId = ""
enable = false
numPosts = 10
width = "100%"
# 为空时自动适配当前主题 i18n 配置
languageCode = "zh_CN"
#  Telegram Comments 评论系统设置
[params.page.comment.telegram]
color = ""
colorful = true
dislikes = false
enable = false
height = ""
limit = 5
outlined = false
siteID = ""
#  Commento 评论系统设置
[params.page.comment.commento]
enable = false
#  utterances 评论系统设置
[params.page.comment.utterances]
enable = false
# owner/repo
darkTheme = "github-dark"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
repo = ""
# giscus comment 评论系统设置 (https://giscus.app/zh-CN)
[params.page.comment.giscus]
# 你可以参考官方文档来使用下列配置
category = "Announcements"
categoryId = "DIC_kwDOLZmgDc4Cdm7x"
enable = true
repo = "pjimming/blog-comment"
repoId = "R_kgDOLZmgDQ"
# 为空时自动适配当前主题 i18n 配置
darkTheme = "preferred_color_scheme"
emitMetadata = "0"
inputPosition = "top"
lang = "zh-CN"
lazyLoading = false
lightTheme = "light"
mapping = "pathname"
reactionsEnabled = "1"
#  第三方库配置
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# 位于 "assets/"
# 或者
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavascript = "some.js"
# 位于 "assets/"
# 或者
# someJavascript = "https://cdn.example.com/some.js"
#  页面 SEO 配置
[params.page.seo]
# 图片 URL
images = []
# 出版者信息
[params.page.seo.publisher]
logoUrl = ""
name = ""

#  TypeIt 配置
[params.typeit]
# 每一步的打字速度 (单位是毫秒)
speed = 100
# 光标的闪烁速度 (单位是毫秒)
cursorSpeed = 1000
# 光标的字符 (支持 HTML 格式)
cursorChar = ""
# 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
duration = 0

# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
baidu = ""
bing = ""
google = ""
pinterest = ""
yandex = ""

#  网站 SEO 配置
[params.seo]
# 图片 URL
image = ""
# 缩略图 URL
thumbnailUrl = ""

#  网站分析配置
[params.analytics]
enable = false
# Google Analytics
[params.analytics.google]
id = ""
# 是否匿名化用户 IP
anonymizeIP = true
# Fathom Analytics
[params.analytics.fathom]
id = ""
# 自行托管追踪器时的主机路径
server = ""
# Plausible Analytics
[params.analytics.plausible]
dataDomain = ""
# Yandex Metrica
[params.analytics.yandexMetrica]
id = ""

#  Cookie 许可配置
[params.cookieconsent]
enable = false
# 用于 Cookie 许可横幅的文本字符串
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""

#  第三方库文件的 CDN 设置
[params.cdn]
# CDN 数据文件名称, 默认不启用
# ["jsdelivr.yml"]
# 位于 "themes/LoveIt/assets/data/cdn/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/data/cdn/"
data = ""

#  兼容性设置
[params.compatibility]
# 是否使用 Polyfill.io 来兼容旧式浏览器
polyfill = false
# 是否使用 object-fit-images 来兼容旧式浏览器
objectFit = false

# Hugo 解析文档的配置
[markup]
# 语法高亮设置
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false 是必要的设置
# (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
# Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# 是否在文档中直接使用 HTML 标签
unsafe = true
# 目录设置
[markup.tableOfContents]
endLevel = 6
startLevel = 2

# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 配置
[Permalinks]
posts = ":year-:month-:day/:filename"
# posts = ":filename"

# 隐私信息配置
[privacy]
#  Google Analytics 相关隐私 (被 params.analytics.google 替代)
[privacy.googleAnalytics]
# ...
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/plain"

# 用于 Hugo 输出文档的设置
[outputs]
# 
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
